8 work
KateKhlynowskaya/autotests_course pull request #5
Opened 2023-06-01 15:13 UTC by KateKhlynowskaya

2023-06-01 17:54 UTC, vlad-vladimirovich requested changes

2023-06-01 17:54 UTC, vlad-vladimirovich commented on Homework8/task_2.py
> +        """проверка корректности данных для построения треугольника"""
в ините не надо ничего писать

2023-06-01 17:54 UTC, vlad-vladimirovich commented on Homework8/task_2.py
> +class Trigon:
дока к классу

2023-06-01 17:54 UTC, vlad-vladimirovich commented on Homework8/task_3.py
> +        return a[0] + a[1] + b[0] + b[1]
return лучше не писать в блоке try вынеси его в else в конец после except

2023-06-01 17:54 UTC, vlad-vladimirovich commented on Homework8/task_3.py
> +        return "".join(reversed(list(str(e))))
e и так строка. зачем строку оборачивать в список и потом присоединять к строке? строку же можно просто срезать

2023-06-01 17:54 UTC, vlad-vladimirovich commented on Homework8/task_2.py
> +            if type(arg) != int:
для проверки типов данных лучше всего использовать isinstance(). type немного о другом

2023-06-01 17:54 UTC, vlad-vladimirovich commented on Homework8/task_1.py
> +        return our_tuple[0] + our_tuple[1]
return лучше не писать в блоке try. вынеси его отдельно

2023-06-02 18:52 UTC, KateKhlynowskaya commented on Homework8/task_3.py
> +        return a[0] + a[1] + b[0] + b[1]
вынесла за try, не не поняла про else

2023-06-02 18:54 UTC, KateKhlynowskaya commented on Homework8/task_3.py
> +        return "".join(reversed(list(str(e))))
e - TypeError, если взять у него срез, то будет ошибка "TypeError: 'TypeError' object is not subscriptable", поэтому привожу к строке

2023-06-02 19:49 UTC, vlad-vladimirovich approved these changes

2023-06-02 19:51 UTC, vlad-vladimirovich approved these changes

2023-06-07 05:51 UTC, merged